baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
enableGitInfo = true

[params]
contentTypeName = "posts"
themeColor = "green"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = true
showLastUpdated = true
favicon = "favicon.ico"
updatedDatePrefix = "Updated"

[languages]
[languages.en]
languageName = "English"
title = "Raroh73"
subtitle = ""
owner = "Raroh73"
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "Raroh73"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
